### ISSUE TITLE
Parts need unique names to allow for auto routing

### ISSUE THREAD

**Issue by spuder** [UltimateHackingKeyboard/electronics#29]
If you attempt to run the auto router, you will get the following errors

<img width="44" alt="screenshot 2016-01-18 23 10 28" src="https://cloud.githubusercontent.com/assets/242382/12411103/b3382a0c-be38-11e5-8396-0ff7dc605cce.png">
<img width="369" alt="screenshot 2016-01-18 23 10 33" src="https://cloud.githubusercontent.com/assets/242382/12411104/b5015c8c-be38-11e5-84f0-f0fa3c738988.png">

<img width="493" alt="screenshot 2016-01-18 20 53 31" src="https://cloud.githubusercontent.com/assets/242382/12411091/94f692f4-be38-11e5-9295-d56802ea9fe6.png">

<img width="491" alt="screenshot 2016-01-18 21 04 40" src="https://cloud.githubusercontent.com/assets/242382/12411092/9628a7de-be38-11e5-821b-c606c976e0ec.png">

The first is caused because the holes do not have unique values

The latter is because every via has the same value

**Comment by mondalaci** [comment]
I wasn't aware of this issue but I'm not concerned about it because the autorouter is practically useless for complicated designs like the UHK.

I rather wouldn't care about these issues because it would require us to individually name the reference designators of holes and vias which would result in increased mainteance burden on the long run for no real benefit.
