### ISSUE TITLE
USB line impedance seems to be really bad

### ISSUE THREAD

**Issue by dpiegdon** [UltimateHackingKeyboard/electronics#41]
In the PCB production version the USB signals are of *very* low quality. That probably explains some of the USB issues I have seen over the last months using my two UHKs.

![UHK-USB-signal](https://user-images.githubusercontent.com/1155873/64740432-def8f380-d4e4-11e9-8a35-30114d45dc54.png)

In this capture, a reference signal (orange) is compared to the UHKs signal (yellow). An impedance mismatch is obvious. The signal corresponds to a UHK keyboard with stock USB cable connected to a USB port with an immediate transceiver. When connecting other devices to this setup, the signal looks almost like the reference.

I have a few suggestions for the next PCB revision (if there will be one, which I really hope):

* check USB design guidelines and trace impedance, esp. for any specifics for the microcontroller used. ( https://www.nxp.com/docs/en/supporting-information/Universal-Serial-Bus-Training.pdf )
* avoid layer hops whereever possible. at first glance, it seems feasible to move C13, R3 and D14 to the top layer and reroute the USB trace along their old position. that would reduce via-count by two per trace.
* avoid dangling traces. currently there are traces going from the USB port J1 north to the board edge. these are probably for electrical testing, QA and firmware flashing? maybe for these two a simple bed of nails and two in-line testbeds can be used? -- I just tested cutting off these traces, without any visible impact. so that probably is not not neccessary at 12MHz.

I know that these recommendations are coming very late and that you very likely already know about these issues and have thought about how to fix those, if ever. But I was missing any reference on the USB issues I have seen and thought that there should be at least a ticket on this.

Just for completeness, here are a few things I have seen over the last month:

* Linux: plenty of bursts of "hid-generic 0003:051D:0002.0006: control queue full" in dmesg. those come all day long. (thats probably a software/firmware bug, but I am not sure)
* when booting up, I sometimes had the problem that the system does not start properly at all. it just hangs in the bios. seems to have gotten better by using a USB hub inbetween.
* random USB disconnects and reconnects (only rarely)

**Comment by dpiegdon** [comment]
Oh I forgot to note down the version. On the PCB there is a sticker with:

UHK60 V7.8
02578
2018/09/28

**Comment by mondalaci** [comment]
Thanks so much for your detailed feedback, and sorry about the issues you've experienced, David!

Admittedly, we haven't examined USB line impedance thoroughly because USB has been very stable for most so far. We've received about a dozen reports which may be related to this, and so far each of them could be solved by connecting the UHK via a (powered?) USB hub, not connecting it via a hub, or using a less noisy power supply.

The dangling traces are for testing, indeed. We'd leave them the way they are, especially if they don't make a change because they're very useful for factory testing.

I'm closing this issue because we can't do anything for the current UHK revision, but we'll make a better job for the next revision.
