### ISSUE TITLE
Reduce resistor values on the TX and RX lines

### ISSUE THREAD

**Issue by spuder** [UltimateHackingKeyboard/electronics#6]
Reduce resistor values on the TX and RX lines of the board-to-board connectors because they didn't work on the 5.1 generation prototypes

**Comment by spuder** [comment]
R7 => 10K
R8 => 10K
R9 => 100K
R10 => 10K

What values should these be? 

<img width="752" alt="screen shot 2015-12-12 at 5 26 59 pm" src="https://cloud.githubusercontent.com/assets/242382/11764652/3540903a-a0f6-11e5-88e2-1cee30bffecc.png">

**Comment by mondalaci** [comment]
Great question! I'm fairly clueless about analog electronics so a professional electronics engineer will revise the design before manufacturing and fix such issues.

In any case, I should add detailed instructions about using the UGL and Opendous KiCad libraries because they're not added by default, which can be seen on the attached picture.

**Comment by spuder** [comment]
I was just asking about those libraries in #22

**Comment by mondalaci** [comment]
This has been redesigned.
